### ISSUE TITLE
Student can't answer the question

### ISSUE THREAD

**Issue by mudrd8mz** [Edunao/moodle-mod_masks#7] opened 2017-03-08 15:45 UTC
After clicking the question box mask, the PDF just gets grey. In the browser console I can see that the script mod/masks/frame_click_mask.php dies with status 404. Further debugging shows that there is another DB related exception thrown when clicking the question box, again related to the "user" being reserved keyword on PostgreSQL.

```
Debug info: ERROR: syntax error at or near "user"
LINE 1: INSERT INTO mdl_masks_user_state (user,question,state,failco...
^
INSERT INTO mdl_masks_user_state (user,question,state,failcount,firstview,lastupdate) VALUES($1,$2,$3,$4,$5,$6) RETURNING id
[array (
'user' => '3',
'question' => 1,
'state' => 16,
'failcount' => 0,
'firstview' => 1488987742,
'lastupdate' => 1488987742,
)]
Error code: dmlwriteexception
￼×Stack trace:
line 482 of /lib/dml/moodle_database.php: dml_write_exception thrown
line 242 of /lib/dml/pgsql_native_moodle_database.php: call to moodle_database->query_end()
line 886 of /lib/dml/pgsql_native_moodle_database.php: call to pgsql_native_moodle_database->query_end()
line 934 of /lib/dml/pgsql_native_moodle_database.php: call to pgsql_native_moodle_database->insert_record_raw()
line 442 of /mod/masks/database_interface.class.php: call to pgsql_native_moodle_database->insert_record()
line 338 of /mod/masks/mask_type.class.php: call to mod_masks\database_interface->updateUserQuestionState()
line 91 of /mod/masks/mask_type_qtxt.class.php: call to mod_masks\mask_type->renderQuestionPage()
line 88 of /mod/masks/frame_click_mask.php: call to mod_masks\mask_type_qtxt->onClickMask()
```

**Comment by Edunao** [comment] 2017-05-11 01:24
I'm considering this one to be a  duplicate of the previously closed POSTGRE issue.
My retesting has gone entirely successfuly.

**Closed as completed by Edunao** 2017-05-11 01:24 UTC
